### ISSUE TITLE
There are some URLs that still use drupalcamp-spain-2015

### ISSUE THREAD

**Issue by DavidHernandez** [AsociacionDrupalES/DrupalCampEs#148] opened 2016-02-09 14:03 UTC
Review and fix it.

**Comment by fran** [comment] 2016-02-09 19:35
In url aliases I can't find any path with drupalcamp-spain-2015. In other hand, there are redirection defined from drupalcamp-spain-2015* to the correct path in the site, so is not a bug. I also checked created contents and I didn't find any url to 2015.
@capynet @DavidHernandez  Do you know a url/content/whatever with drupalcamp-spain-2015 ? I would like to test it before close the issue.

**Comment by capynet** [comment] 2016-02-11 15:17
Yes franSeva, please look
http://2016.drupalcamp.es/es/drupalcamp-spain-2015/sponsors

2016-02-09 20:35 GMT+01:00 Francisco José Seva mora <
notifications@github.com>:

> In url aliases I can't find any path with drupalcamp-spain-2015. In other
> hand, there are redirection defined from drupalcamp-spain-2015* to the
> correct path in the site, so is not a bug. I also checked created contents
> and I didn't find any url to 2015.
> @capynet <https://github.com/capynet> @DavidHernandez
> <https://github.com/DavidHernandez> Do you know a url/content/whatever
> with drupalcamp-spain-2015 ? I would like to test it before close the
> issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AsociacionDrupalES/DrupalCampEs/issues/148#issuecomment-182024136>
> .
>



-- 
Marcelo.
Skype: *capynet*
Móvil: *697 295 042*

**Closed** 2016-02-18 15:02 UTC
Labels: High Priority
