### ISSUE TITLE
Review responsiveness on iPhones

### ISSUE THREAD

**Issue by DavidHernandez** [AsociacionDrupalES/DrupalCampEs#70] opened 2015-03-30 11:41 UTC
Seems that the theme is broken when browsing the website using iThings: https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/128746/934491/RRdLbu2TyEDvcKZ/upload.png

Can this be reviewed and fixed?

**Comment by DavidHernandez** [comment] 2015-03-30 11:41
Seems to be in iPhone 5 running iOS 8.

**Comment by NITEMAN** [comment] 2015-03-30 12:06
Aditional data, it seems to happen only in Facebook's in-app browser

**Comment by capynet** [comment] 2015-04-01 20:11
I tested on native IOS devices and cant find this error... What's the url?

**Comment by capynet** [comment] 2015-04-10 04:20
Closing this issue. cant reproduce. On iphone works well :)

**Closed by capynet** 2015-04-10 04:20 UTC
Labels: bug, help wanted
